version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /NASshare/nextcloud/config:/config
      - /NASshare/nextcloud/:/data
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
