version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /NASshare/nextcloud/config:/config
      - /NASshare/nextcloud/:/data
    ports:
      - 8071:80
      - 445:443
    restart: unless-stopped
